### ISSUE TITLE
Unable to use RL Lib agents

### ISSUE THREAD

**Issue by XkunW** [rdnfn/beobench#102]
### Problem

When using RL lib agents in config file, Beobench complains `/usr/bin/python: can't find '__main__' module in '/root/beobench_configs/rllib.py'`

**Comment by rdnfn** [comment]
Thanks for raising this issue, I am unfortunately unable to replicate this problem - with v0.5.4 all RLlib tests pass. Please reraise this issue if it should still occur with v0.5.4 (to be released today).
