### ISSUE TITLE
Create integration with energym

### ISSUE THREAD

**Issue by rdnfn** [rdnfn/beobench#21]
### Feature Description

Make [energym package](https://github.com/bsl546/energym) accessible via beobench.

# Minimum features:
- [x]  action convertor function
- [x]  obs convertor function
- [x]  reset function
- [x] default reward functions (that works out of the box)

Later:
- [x]  norm obs wrapper
- [x]  norm action wrapper

Later later:
- [x] discrete action wrapper

For Arduin:
- [x] set up functioning docker container for energym

**Comment by enjeeneer** [comment]
All done!
