### ISSUE TITLE
Add support for custom reward function

### ISSUE THREAD

**Issue by enjeeneer** [rdnfn/beobench#28]
### Problem

Currently user cannot define their own reward function

### Solution

Create wrapper function that updates default environment reward functions with user specified function.

**Comment by rdnfn** [comment]
Wrappers will be supported with v0.4.4. Thus closing this issue.

See [this file](https://github.com/rdnfn/beobench/blob/13f9c4727e81469e28d441aee9a48bbadd3aa5ea/beobench/wrappers/energym.py) for an example of how to use wrappers to create custom rewards in energym now.
