### ISSUE TITLE
No files saved in beobench_result directory

### ISSUE THREAD

**Issue by HYDesmondLiu** [rdnfn/beobench#88]
### Problem
In `config.yaml`, `general` section, there is a `local_dir`,
 which is commented  `# save experiment data to ``./beobench_results`` directory`.
However, if I try to save e.g. a numpy array of rewards. It is nowhere to be found.
May I know where the generated files are located? Where and how should I specify a directory to save files in `agent.py` or `config.yaml`?

**Comment by rdnfn** [comment]
Hi @HYDesmondLiu, great question! The docs definitely need some clarification here. 

The answer is that the `local_dir` only refers to the directory to save data to on the host machine (the machine where you call `beobench run`). This directory is mounted in the experiment container. Inside the experiment container this directory is accessibe under the path `/root/beobench_results/`. So in your `agent.py` script you can save files to `/root/beobench_results/` (inside the experiment container) and then these will be saved to `local_dir` on your host machine set in the `config.yaml`. 

Hope this helps! Let me know if this solved the issue.

**Comment by HYDesmondLiu** [comment]
@rdnfn 
    Thanks for the response. 
However, I am a non-root user. I have tried to generate files with an absolute path and did not work. 
Is there any other workaround for this?

**Comment by rdnfn** [comment]
Sorry for the delay but for completeness (if it could help another user): the root user only refers to inside the experiment container (irrespective of your user on the host machine). Closing this issue now, but feel free re-raise this issue if the problem persists.
