### ISSUE TITLE
Sinergym latest update breaks BeoBench

### ISSUE THREAD

**Issue by XkunW** [rdnfn/beobench#96]
### Problem

The [latest commit](https://github.com/ugr-sail/sinergym/commit/aa9c3fdac209e323eba2254be093b3c7f8b8b322#diff-d8acf798c1850f4f64984a5dbcaac82b6599128efa8b924a85cf234629dde69a) in the sinergym repo removed the `RANGES_IW` constant in `sinergym/sinergym/utils/constants.py`, which causes an import error when running BeoBench in sinergym environments:
```
Beobench ⚡️container:   File "/opt/beobench/experiment_setup/env_creator.py", line 7, in <module>
Beobench ⚡️container:     from sinergym.utils.constants import RANGES_5ZONE, RANGES_IW, RANGES_DATACENTER
Beobench ⚡️container: ImportError: cannot import name 'RANGES_IW' from 'sinergym.utils.constants' (/sinergym/sinergym/utils/constants.py)
```

### Potential Solution

Update the default `create_env` function for sinergym environments

**Comment by rdnfn** [comment]
@XkunW thanks again for raising this issue and suggesting the solution. Working on adding your fix to a new release. Will close this issue once the release has been published.

**Comment by XkunW** [comment]
@rdnfn Thanks for the quick reply. In the meantime, I'm trying to use my local dev version of beobench, but I keep getting the error saying 
`ValueError: Beobench config requests version 0.5.2 that does not match installed version 0.5.1. Change the installed Beobench version to the requested version 0.5.2 or remove general.version parameter from config to prevent this error.`
My dev beobench version is 0.5.2 and I'm not sure how to fix this version misalignment. I'm wondering if you could provide some insight on how to resolve this error? Thanks!

**Comment by rdnfn** [comment]
Great question, I created another issue (#98) for your comment above.

Note that now v0.5.3 has been released, so hopefully you should be able to use that one. Closing this issue. Feel free to reopen if not fully resolved. Thanks for your help!
