### ISSUE TITLE
Unable to log messages in console during agent training

### ISSUE THREAD

**Issue by XkunW** [rdnfn/beobench#99]
### Problem

With version 0.5.3, I've noticed that the logging module in my agent script is no longer printing any messages in the console. I've also tried using `print()` and the BeoBench logger, but neither is working.

**Comment by rdnfn** [comment]
Hi @XkunW, thanks for raising this issue!

I think this issue is because `subprocess.check_call` was replaced with `subprocess.check_output` in the main `beobench.experiment.scheduler.run()` method.

Will look into reverting this change, as I currently do not see a benefit of running it this way.
